### ISSUE TITLE
Use copysign?

### ISSUE THREAD

**Issue by dpsanders** [JeffreySarnoff/AdjacentFloats.jl#6]
Maybe using `copysign` instead of the ternary operator, to avoid the branch, may be more efficient?

**Comment by JeffreySarnoff** [comment]
I will put in the emendations tonight.

**Comment by dpsanders** [comment]
See #7.

It is not clear to me what the 5.0e-324 is there for?

**Comment by JeffreySarnoff** [comment]
Its there to make it be more often correct for very small values.
I have to rerun this for timing -- the choices I made at the time were a
balance of accuracy and quickness.

On Tue, May 30, 2017 at 10:13 AM, David P. Sanders <notifications@github.com

**Comment by JeffreySarnoff** [comment]
this is done -- I am keeping it open for reference and as a reminder (and new version tagged)

**Comment by JeffreySarnoff** [comment]
done
